### ISSUE TITLE
try to work out why we cant convert to issue.

### ISSUE THREAD

**Issue by Pgarza-dev** [AnaCascante/development-platforms#10]
**This issue has to be fixed by Ana by following the steps...**

1. Open the repo and head to settings

![Image](https://github.com/AnaCascante/development-platforms/assets/84074301/bb3f1f05-8dc8-456f-9a19-644993bd78bc)

2. In settings, scroll down to FEATURES and tick the ISSUES box. This will allow the repo to be found in the options when choosing a project to add the issues too.

![Image](https://github.com/AnaCascante/development-platforms/assets/84074301/4b60059f-4a71-42d9-ab92-c0f105fc1275)

**Comment by AnaCascante** [comment]
issue is fixed :) thank you Pablo ❤
