### ISSUE TITLE
Get to know sanity

### ISSUE THREAD

**Issue by Pgarza-dev** [AnaCascante/development-platforms#12]
Read and watch videos on sanity.

- [ ] https://www.youtube.com/watch?v=OcTPaUfay5I&t=122s
- [ ] https://www.youtube.com/@sanity_io
- [ ] https://youtu.be/bDVAQZVeebw?si=GWPfpaKmRXBGwKWW&t=408

Read Joakims ca. 
- [ ] https://github.com/NoroffFEU/development-platforms/pull/125/files/3b4b1c577319ecf64892b0a4875a692b19c857b2

**Comment by AnaCascante** [comment]
we have now some knowledge on sanity
