### ISSUE TITLE
Add images for set up references

### ISSUE THREAD

**Issue by Pgarza-dev** [AnaCascante/development-platforms#4]
For this ticket I will add images that will help in referencing the setup of Sanity using vanilla JS and HTML as well as references for setup with Next.js

[ x ] add images for HTML / JS setup
[ x ] add images for NEXT.JS set up
[ x ] add images for sanity studio create project icon
[ x ] add images for where to add new CORS url
[ x ] add image for where to locate project ID for client
[ x ] add image for sanity studio display

**Comment by Knirkeli** [comment]
Grate addition!
